### ISSUE TITLE
eye-tracking

### ISSUE THREAD

**Issue by mochic** [AllenInstitute/np_config#3]
- [x] get raw mp4s into lims eye-tracking queue
- [x] get .h5 output into sdk modules/functions
- [x] create 'add_to_existing_nwb' func 
- [x] add to assembly repo
- [ ] verfiy gaze tracking is correct before adding

![Image](https://user-images.githubusercontent.com/63425812/242425411-fcc41d5b-777e-432f-a233-f59e0b41afce.jpg)
